package ai.nervemind.plugin.api;

import java.time.Instant;

/**
 * Base class for all system events.
 * 
 * <p>
 * Events are generated by the system and can be subscribed to by plugins.
 * This base class provides common properties like timestamp and event type.
 * </p>
 * 
 * <h2>Event Types</h2>
 * <ul>
 * <li>Workflow events - started, completed, failed</li>
 * <li>Execution events - node executed, execution completed</li>
 * <li>Application events - started, stopped, settings changed</li>
 * <li>Plugin events - loaded, unloaded, error</li>
 * </ul>
 * 
 * @author NerveMind Team
 * @since 1.0.0
 * @see EventHandler
 * @see EventType
 */
public abstract class Event {

    private final EventType type;
    private final Instant timestamp;
    private final String source;
    private final boolean cancellable;

    /**
     * Creates a new event.
     * 
     * @param type        the event type
     * @param source      the source of the event (e.g., workflow ID, node ID)
     * @param cancellable whether the event can be cancelled
     */
    protected Event(EventType type, String source, boolean cancellable) {
        this.type = type;
        this.timestamp = Instant.now();
        this.source = source;
        this.cancellable = cancellable;
    }

    /**
     * Gets the event type.
     * 
     * @return the event type
     */
    public EventType getType() {
        return type;
    }

    /**
     * Gets the timestamp when this event occurred.
     * 
     * @return the timestamp
     */
    public Instant getTimestamp() {
        return timestamp;
    }

    /**
     * Gets the source of this event.
     * 
     * <p>
     * The source identifies what generated the event.
     * For workflow events, this is typically the workflow ID.
     * For node events, this is the node ID.
     * </p>
     * 
     * @return the source identifier
     */
    public String getSource() {
        return source;
    }

    /**
     * Checks if this event can be cancelled.
     * 
     * <p>
     * If an event is cancellable, handlers can call {@link #cancel()}
     * to prevent the default behavior.
     * </p>
     * 
     * @return true if the event is cancellable
     */
    public boolean isCancellable() {
        return cancellable;
    }

    /**
     * Checks if this event has been cancelled.
     * 
     * @return true if cancelled
     */
    public boolean isCancelled() {
        return cancelled;
    }

    private boolean cancelled = false;

    /**
     * Cancels this event if it is cancellable.
     * 
     * @throws IllegalStateException if the event is not cancellable
     */
    public void cancel() {
        if (!cancellable) {
            throw new IllegalStateException("This event cannot be cancelled");
        }
        this.cancelled = true;
    }

    /**
     * Gets a human-readable description of this event.
     * 
     * @return the event description
     */
    public abstract String getDescription();

    @Override
    public String toString() {
        return String.format("%s[type=%s, source=%s, time=%s]",
                getClass().getSimpleName(), type, source, timestamp);
    }
}
